import { DM_Sans } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  console.log(session?.user);
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>{children}</body>
    </html>
  );
}
